apiVersion: v1
kind: ConfigMap
metadata:
  name: app-setting
data:
  key: value
  prop1: prop1value
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: app-setting
      args:
        - /bin/sh
        - "-c"
        - "echo $(prop1)"
  restartPolicy: Never



