apiVersion: v1
kind: ConfigMap
metadata:
  name: app-setting
data:
  prop1: prop1value
---
apiVersion: v1
kind: Secret
metadata:
  name: app-password
type: Opaque
data:
  prop2: dGVzdHBhc3N3b3Jk
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: app-setting
        - secretRef:
            name: app-password
      args:
        - /bin/sh
        - "-c"
        - "echo $(prop1); echo $(prop2); echo test"
  restartPolicy: Never



