apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-demo
  labels:
    app: hello-demo
    version: v1
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 2
  minReadySeconds: 6
  selector:
    matchLabels:
      app: hello-demo
  template:
    metadata:
      labels:
        app: hello-demo
        version: v1
    spec:
      containers:
        - name: hello-demo
          image: hello-demo:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-demo-svc
spec:
  type: LoadBalancer
  selector:
    app: hello-demo
  ports:
    - name: http
      port: 8080
      protocol: TCP
